environment:
  global:
    CRATE_NAME: rustfmt
    DEPLOY_VERSION: nightly
    RUST_VERSION: nightly
  matrix:
    - TARGET: i586-pc-windows-msvc
    - TARGET: i686-pc-windows-gnu
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: x86_64-pc-windows-msvc

install:
  - git submodule update --init --recursive
  - ps: ci\install.ps1

build: false

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      ( exit 0 )
    ) else (
      if [%RUST_VERSION%]==[%DEPLOY_VERSION%] (
        cargo rustc --manifest-path rustfmt/Cargo.toml --target %TARGET% --release --bin cargo-fmt -- -C lto &&
        cargo rustc --manifest-path rustfmt/Cargo.toml --target %TARGET% --release --bin rustfmt -- -C lto
      )
    )

before_deploy:
  - ps: ci\package.ps1

deploy:
  description: 'Windows release'
  artifact: /.*\.zip/
  auth_token:
    secure: dRmstFq9p25R+YAZ2mWU/ghxQyOxfKEdhFjXXGjKzdWcoa0BodgAjV/VEDa0nTnA
  provider: GitHub
  on:
    RUST_VERSION: nightly
    appveyor_repo_tag: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - auto
    - try

notifications:
  - provider: Email
    on_build_success: false
